name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Check dist content
        run: ls -la dist/ || dir dist/  # List files in dist
      - name: Copy product details page to root
        run: |
          if [ -f dist/product_pages/index.html ]; then
            cp dist/product_pages/index.html dist/index.html
            echo "Copied product_pages/index.html to index.html"
          else
            echo "Error: dist/product_pages/index.html not found"
            exit 1
          fi
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}